# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rapida.artifacts.protos.talk_api_pb2 as talk__api__pb2


class TalkServiceStub(object):
    """



    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAssistantMessage = channel.unary_stream(
                '/talk_api.TalkService/CreateAssistantMessage',
                request_serializer=talk__api__pb2.CreateAssistantMessageRequest.SerializeToString,
                response_deserializer=talk__api__pb2.CreateAssistantMessageResponse.FromString,
                )
        self.GetAllAssistantConversaction = channel.unary_unary(
                '/talk_api.TalkService/GetAllAssistantConversaction',
                request_serializer=talk__api__pb2.GetAllAssistantConversactionRequest.SerializeToString,
                response_deserializer=talk__api__pb2.GetAllAssistantConversactionResponse.FromString,
                )
        self.GetAllConversactionMessage = channel.unary_unary(
                '/talk_api.TalkService/GetAllConversactionMessage',
                request_serializer=talk__api__pb2.GetAllConversactionMessageRequest.SerializeToString,
                response_deserializer=talk__api__pb2.GetAllConversactionMessageResponse.FromString,
                )


class TalkServiceServicer(object):
    """



    """

    def CreateAssistantMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllAssistantConversaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllConversactionMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TalkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAssistantMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.CreateAssistantMessage,
                    request_deserializer=talk__api__pb2.CreateAssistantMessageRequest.FromString,
                    response_serializer=talk__api__pb2.CreateAssistantMessageResponse.SerializeToString,
            ),
            'GetAllAssistantConversaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllAssistantConversaction,
                    request_deserializer=talk__api__pb2.GetAllAssistantConversactionRequest.FromString,
                    response_serializer=talk__api__pb2.GetAllAssistantConversactionResponse.SerializeToString,
            ),
            'GetAllConversactionMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllConversactionMessage,
                    request_deserializer=talk__api__pb2.GetAllConversactionMessageRequest.FromString,
                    response_serializer=talk__api__pb2.GetAllConversactionMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'talk_api.TalkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TalkService(object):
    """



    """

    @staticmethod
    def CreateAssistantMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/talk_api.TalkService/CreateAssistantMessage',
            talk__api__pb2.CreateAssistantMessageRequest.SerializeToString,
            talk__api__pb2.CreateAssistantMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllAssistantConversaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/talk_api.TalkService/GetAllAssistantConversaction',
            talk__api__pb2.GetAllAssistantConversactionRequest.SerializeToString,
            talk__api__pb2.GetAllAssistantConversactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAllConversactionMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/talk_api.TalkService/GetAllConversactionMessage',
            talk__api__pb2.GetAllConversactionMessageRequest.SerializeToString,
            talk__api__pb2.GetAllConversactionMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
