repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.3.0'
  hooks:
  - id: check-merge-conflict
- repo: https://github.com/asottile/yesqa
  rev: v1.3.0
  hooks:
  - id: yesqa
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    language_version: python3 # Should be a command that runs python3.6+
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.3.0'
  hooks:
  - id: end-of-file-fixer
    exclude: >-
      ^rapida-python\/setup\.cfg$
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    types: [python]
  - id: file-contents-sorter
    files: |
      CONTRIBUTORS.txt|
      docs/spelling_wordlist.txt|
      .gitignore|
      .gitattributes
  - id: check-case-conflict
  - id: check-json
  - id: check-xml
  - id: check-executables-have-shebangs
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: check-added-large-files
  - id: check-symlinks
  - id: debug-statements
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  - id: detect-private-key
    exclude: ^examples|(?:tests/ssl)/
- repo: https://github.com/asottile/pyupgrade
  rev: 'v2.34.0'
  hooks:
  - id: pyupgrade
    args: ['--py36-plus', '--keep-mock']
- repo: https://github.com/PyCQA/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    exclude: ^(artifacts|examples)/
    args: ['--ignore=E501']
- repo: https://github.com/Lucas-C/pre-commit-hooks-markup
  rev: v1.0.1
  hooks:
  - id: rst-linter
    files: >-
      ^[^/]+[.]rst$
