# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rapida/artifacts/protos/endpoint_service/invoker-api.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:rapida/artifacts/protos/endpoint_service/invoker-api.proto\x12\x0c\x65ndpoint_api\x1a\x1cgoogle/protobuf/struct.proto\"Q\n\x0cInvokerError\x12\x15\n\terrorCode\x18\x01 \x01(\x04\x42\x02\x30\x01\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\x12\x14\n\x0chumanMessage\x18\x03 \x01(\t\"<\n\x11\x45ndpointDefnition\x12\x16\n\nendpointId\x18\x01 \x01(\x04\x42\x02\x30\x01\x12\x0f\n\x07version\x18\x02 \x01(\t\"3\n\x0eOverrideOption\x12\x12\n\noptionName\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x98\x01\n\rInvokeRequest\x12\x31\n\x08\x65ndpoint\x18\x01 \x01(\x0b\x32\x1f.endpoint_api.EndpointDefnition\x12%\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12-\n\x07options\x18\x03 \x03(\x0b\x32\x1c.endpoint_api.OverrideOption\"\x90\x01\n\x0eInvokeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12.\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x1a.endpoint_api.InvokerErrorH\x00\x88\x01\x01\x42\x08\n\x06_error\"L\n\x0cProbeRequest\x12\x15\n\trequestId\x18\x01 \x01(\x04\x42\x02\x30\x01\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x8f\x01\n\rProbeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12.\n\x05\x65rror\x18\x04 \x01(\x0b\x32\x1a.endpoint_api.InvokerErrorH\x00\x88\x01\x01\x42\x08\n\x06_error2\x93\x01\n\nDeployment\x12\x43\n\x06Invoke\x12\x1b.endpoint_api.InvokeRequest\x1a\x1c.endpoint_api.InvokeResponse\x12@\n\x05Probe\x12\x1a.endpoint_api.ProbeRequest\x1a\x1b.endpoint_api.ProbeResponseB7Z5github.com/lexatic/web-backend/protos/lexatic-backendb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rapida.artifacts.protos.endpoint_service.invoker_api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/lexatic/web-backend/protos/lexatic-backend'
  _globals['_INVOKERERROR'].fields_by_name['errorCode']._options = None
  _globals['_INVOKERERROR'].fields_by_name['errorCode']._serialized_options = b'0\001'
  _globals['_ENDPOINTDEFNITION'].fields_by_name['endpointId']._options = None
  _globals['_ENDPOINTDEFNITION'].fields_by_name['endpointId']._serialized_options = b'0\001'
  _globals['_PROBEREQUEST'].fields_by_name['requestId']._options = None
  _globals['_PROBEREQUEST'].fields_by_name['requestId']._serialized_options = b'0\001'
  _globals['_INVOKERERROR']._serialized_start=106
  _globals['_INVOKERERROR']._serialized_end=187
  _globals['_ENDPOINTDEFNITION']._serialized_start=189
  _globals['_ENDPOINTDEFNITION']._serialized_end=249
  _globals['_OVERRIDEOPTION']._serialized_start=251
  _globals['_OVERRIDEOPTION']._serialized_end=302
  _globals['_INVOKEREQUEST']._serialized_start=305
  _globals['_INVOKEREQUEST']._serialized_end=457
  _globals['_INVOKERESPONSE']._serialized_start=460
  _globals['_INVOKERESPONSE']._serialized_end=604
  _globals['_PROBEREQUEST']._serialized_start=606
  _globals['_PROBEREQUEST']._serialized_end=682
  _globals['_PROBERESPONSE']._serialized_start=685
  _globals['_PROBERESPONSE']._serialized_end=828
  _globals['_DEPLOYMENT']._serialized_start=831
  _globals['_DEPLOYMENT']._serialized_end=978
# @@protoc_insertion_point(module_scope)
