name: Build and Publish Golang SDK

on:
  push:
    # paths:
    #   - "rapida-golang/**"
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20" # Adjust to the Go version you are using

      - name: Install dependencies
        run: go mod tidy
        working-directory: rapida-golang

      - name: Build the SDK
        run: go build -v ./...
        working-directory: rapida-golang

  publish:
    name: Publish SDK
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20" # Adjust to the Go version you are using

      - name: Install dependencies
        run: go mod tidy
        working-directory: rapida-golang

      - name: Authenticate to GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Tag version and publish to GitHub Packages
        run: |
          VERSION=$(cat rapida-golang/version.txt)
          git tag v${VERSION}
          git push origin --tags
          go list -m all
