name: Build and Deploy to Maven

on:
  push:
    paths:
      - "rapida-java/**"
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: rapida-java

  deploy:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #   - name: Set up GPG key
      #     run: |
      #       echo "$GPG_PRIVATE_KEY" | gpg --batch --import
      #       echo "use-agent" >> ~/.gnupg/gpg.conf
      #       echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

      #   - name: Configure GPG agent
      #     run: |
      #       echo "default-cache-ttl 600" >> ~/.gnupg/gpg-agent.conf
      #       echo "max-cache-ttl 7200" >> ~/.gnupg/gpg-agent.conf
      #       gpgconf --reload gpg-agent

      #   - name: Export GPG_TTY
      #     run: export GPG_TTY=$(tty)

      #   - name: Set up JDK for Maven Central
      #     uses: actions/setup-java@v3
      #     with:
      #       java-version: "17"
      #       distribution: "temurin"
      #       server-id: ossrh
      #       server-username: ${{ secrets.OSSRH_USERNAME }}
      #       server-password: ${{ secrets.OSSRH_PASSWORD }}

      #   - name: Publish to Maven Central
      #     run: mvn --batch-mode deploy -P ossrh -s ./sonatype-settings.xml -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }}
      #     env:
      #       MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      #       MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      #       GPG_TTY: $(tty)

      - name: Set up Java for GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
          server-id: github
          server-username: ${{ secrets.GITHUB_ACTOR }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: mvn --batch-mode deploy -P github -s ./github-settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: rapida-java
