name: Build and Deploy to Maven

on:
  push:
    paths:
      - "rapida-java/**"
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build with Maven
        run: mvn clean install
        working-directory: rapida-java

  deploy:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Configure Maven for deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: |
          mkdir -p $HOME/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>github</id>
                      <username>oauth2</username>
                      <password>${GITHUB_TOKEN}</password>
                    </server>
                    <server>
                      <id>ossrh</id>
                      <username>${OSSRH_USERNAME}</username>
                      <password>${OSSRH_PASSWORD}</password>
                    </server>
                  </servers>
                  <profiles>
                    <profile>
                      <id>github</id>
                      <repositories>
                        <repository>
                          <id>github</id>
                          <url>https://maven.pkg.github.com/${{ github.repository_owner }}/rapida-java</url>
                        </repository>
                      </repositories>
                    </profile>
                    <profile>
                      <id>ossrh</id>
                      <repositories>
                        <repository>
                          <id>ossrh</id>
                          <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
                        </repository>
                      </repositories>
                    </profile>
                  </profiles>
                  <activeProfiles>
                    <activeProfile>github</activeProfile>
                    <activeProfile>ossrh</activeProfile>
                  </activeProfiles>
                </settings>" > $HOME/.m2/settings.xml

      - name: Deploy to GitHub Packages and OSSRH
        run: mvn clean deploy -DskipTests
        working-directory: rapida-java

  tag:
    runs-on: ubuntu-latest
    needs: deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Tag the release
        run: |
          NEW_TAG=$(date +'%Y%m%d%H%M%S')
          git tag -a "v${NEW_TAG}" -m "Release version ${NEW_TAG}"
          git push origin "v${NEW_TAG}"
