name: Build and Deploy to Maven

on:
  push:
    paths:
      - "rapida-java/**"
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: maven

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: rapida-java

  create-tag:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      actions: write
      attestations: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "maven"

      - name: Extract Maven version
        id: extract_version
        run: |
          echo "Extracting Maven version from pom.xml..."
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Maven project version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV
        working-directory: rapida-java
      - name: Create Git tag
        run: |
          echo "Creating Git tag for version ${{ env.version }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag -a "v${{ env.version }}-java" -m "Release version ${{ env.version }}-java"
          git push origin "v${{ env.version }}-java"
        working-directory: rapida-java

  publish-github:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    needs: create-tag
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "11"
          distribution: "temurin"
      - name: Publish package
        run: mvn -P github --batch-mode deploy -DskipTests
        working-directory: rapida-java
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-ossrh:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    needs: create-tag
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
        #   gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        #   gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish package
        run: mvn -P ossrh --batch-mode deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        working-directory: rapida-java
