name: Build and Publish Python SDK

on:
  push:
    paths:
      - "rapida-python/**"
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
        working-directory: rapida-python

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel
        working-directory: rapida-python

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          twine upload dist/*
        working-directory: rapida-python

  tag:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Tag the release
        id: tag
        run: |
          NEW_TAG=$(date +'%Y%m%d%H%M%S')
          git tag -a "v${NEW_TAG}" -m "Release version ${NEW_TAG}"
          git push origin "v${NEW_TAG}"
